# sample Array With mulit-datatype

# collection: item
[[databases]]
d_name = "database"

# collection: item
[databases.collection]
c_name = "item"
count = 30

# collection: item field:i_id
[[databases.collection.fields]]
constraints = [{type = "objectID"}]
f_name = "i_id"

# collection: item field:name
[[databases.collection.fields]]
constraints = [{type = "string"}]
f_name = "name"

# collection: item field:sampleArray
[[databases.collection.fields]]
f_name = "sampleArray"
# sets = [{value = [[3.14], ["test", "array"]], at = [1, 3]}]
sets = [{value = [3.14, "test", "array"], at = [1, 3]}]

[[databases.collection.fields.constraints]]
element_type = [
  {value = 5, weight = 2},
  {type = "string"},
  {type = "array", element_type = [{type = "boolean"}]},
]
maxItem = 3
type = "array"

# collection: item
# collection: item field:i_id
# collection: item field:name
# collection: item field:sampleArray