.TH "SEESTERNSYNTAX" 7 "13/03/2022" "Version 0.0.3" "Seestern Manual"
.SH NAME
seesternsyntax - A syntax reference for seestern configuration file

.SH SYNOPSIS
seestern *

.SH DESCRIPTION

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eu commodo est.

.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for seestern

.SH GUIDES
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eu commodo est.

.SH SEE ALSO
\fBseestern\fP(1), \fBseesterntutorial\fP(1), \fBseestern-init\fP(1), \fBseestern-generate\fP(1)

.SH SEESTERN
Part of the \fBseestern\fP(1) suite