.TH "SEESTERN" 1 "13/03/2022" "Version 0.0.3" "Seestern Manual"
.SH NAME
seestern - Test Data Generator for Document-Oriented Database

.SH SYNOPSIS
\fIseestern\fR [--help|-h] <command> [<args>]

.SH DESCRIPTION
Seestern is a command-line interface test data generator for Document-Oriented Database tool that capables of listing a database and collection, analyzing and generating configuration file and generating data by specification in the configuration file.

See \fBseesterntutorial\fP(7) to get started, see \fBseesternsyntax\fP(7) for syntax reference for configuration file.

At current version, this tool only support MongoDB.

.SH OPTIONS
\fB-h\fP, \fB--help\fP
.RS 4
help for seestern.
.RE

.SH SEE ALSO
\fBseestern-ps\fP(1), \fBseestern-init\fP(1), \fBseestern-generate\fP(1)

.SH AUTHOR
Chaiyatad Chanasuppakul (chaiyatad@gmail.com)