.TH "SEESTERN-INIT" 1 "13/03/2022" "Version 0.0.3" "Seestern Manual"
.SH NAME
seestern-init - Create a configuration file


.SH SYNOPSIS
\fBseestern init [flags]\fP


.SH DESCRIPTION
Create a configuration file

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eu commodo est.

.SH OPTIONS
\fB-c\fP, \fB--collection\fP=[]
	specific database and collection to create (in \&. format)

\fB-s\fP, \fB--connectionString\fP=""
	connection string to database

\fB-h\fP, \fB--help\fP[=false]
	help for init

\fB-o\fP, \fB--output\fP=""
	path to create output file

\fB-t\fP, \fB--type\fP="yaml"
	file type of output file (json, yaml, toml)

\fB-v\fP, \fB--verbose\fP[=false]
	verbose output

.SH SEE ALSO
\fBseestern-ps(\fP1), \fBseestern-generate\fP(1)

.SH SEESTERN
Part of the \fBseestern\fP(1) suite