.TH "SEESTERN-GENERATE" 1 "13/03/2022" "Version 0.0.3" "Seestern Manual"
.SH NAME
seestern-generate - Generate a test data from configuration file

.SH SYNOPSIS
\fBseestern generate [flags]\fP


.SH DESCRIPTION
Generate a test data from configuration file

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eu commodo est.

.SH OPTIONS
\fB-s\fP, \fB--connectionString\fP=""
	connection string to database

\fB-d\fP, \fB--drop\fP[=false]
	drop all document in collection in configuration file

\fB-f\fP, \fB--file\fP=""
	path to configuration file

\fB-h\fP, \fB--help\fP[=false]
	help for generate

\fB-i\fP, \fB--insert\fP[=false]
	insert document in collection in configuration file

\fB-o\fP, \fB--output\fP=""
	path to save generate data

\fB-v\fP, \fB--verbose\fP[=false]
	verbose output

.SH SEE ALSO
\fBseestern-ps\fP(1), \fBseestern-init\fP(1)

.SH SEESTERN
Part of the \fBseestern\fP(1) suite