.TH "SEESTERN" 1 "13/03/2022" "Version 0.0.3" "Seestern Manual"
.SH NAME
seestern - Test Data Generator for Document-Oriented Database

.SH SYNOPSIS
\fIseestern\fR [--help]

.SH DESCRIPTION
Test Data Generator for Document-Oriented Database

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eu commodo est.

.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for seestern

.SH GUIDES
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eu commodo est.

.SH SEE ALSO
\fBseestern-ps\fP(1), \fBseestern-init\fP(1), \fBseestern-generate\fP(1)

.SH AUTHOR
Chaiyatad Chanasuppakul (chaiyatad@gmail.com)