.TH "SEESTERN-PS" 1 "13/03/2022" "Version 0.0.3" "Seestern Manual"
.SH NAME
seestern-ps - List collections of given connection string

.SH SYNOPSIS
\fBseestern ps [flags]\fP

.SH DESCRIPTION
List collections of given connection string

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eu commodo est.

.SH OPTIONS
\fB-s\fP, \fB--connectionString\fP=""
	connection string to database

\fB-d\fP, \fB--database\fP=""
	specific database to list collection

\fB-h\fP, \fB--help\fP[=false]
	help for ps

.SH SEE ALSO
\fBseestern-init\fP(1), \fBseestern-generate\fP(1)

.SH SEESTERN
Part of the \fBseestern\fP(1) suite